# Generated by Django 3.1.7 on 2021-02-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsaCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UsaRealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
                ('street_address', models.CharField(blank=True, max_length=256, null=True)),
                ('locality', models.CharField(blank=True, max_length=64, null=True)),
                ('pincode', models.CharField(blank=True, max_length=64, null=True)),
                ('website', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.usacity')),
            ],
        ),
        migrations.AddField(
            model_name='usacity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.usastate'),
        ),
    ]
